name: Register algolia

on:
  push:
    branches: [main]
    paths: ['posts/**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Create .env

        run: |
          touch .env
          echo NEXT_PUBLIC_ALGOLIA_APP_ID=${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID}} >> .env
          echo ALGOLIA_ADMIN_KEY=${{ secrets.ALGOLIA_ADMIN_KEY}} >> .env
      - name: npm install
        run: npm install

      - name: Run algolia script
        run: npm run algolia
      - name: Commit and push
        run: |
          git config --local user.name 'ryo_of_the_ryo'
          git config --local user.email 'ryomasumura1201@gmail.com'
          git add .
          git commit --allow-empty -m "Run algolia"
          git push
